elasticsearch to magento 2.4 and added mariadb

diff --git a/bin/dev_command/create b/bin/dev_command/create
--- a/bin/dev_command/create
+++ b/bin/dev_command/create
@@ -82,40 +82,40 @@ function install() {
 }
 
 function configureDb() {
-  setEnv;
-  if [ -z $PROJECT ]; then
-    printf '%s\n' "ERROR: Please enter PROJECT name" >&2
-    exit 1
-  fi
+  # setEnv;
+  # if [ -z $PROJECT ]; then
+  #   printf '%s\n' "ERROR: Please enter PROJECT name" >&2
+  #   exit 1
+  # fi
 
-  cd $STORE_DIR
-  echo "### IMPORT CONFIG ###"
-  dev magerun2 app:config:import
+  # cd $STORE_DIR
+  # echo "### IMPORT CONFIG ###"
+  # dev magerun2 app:config:import
 
 
-  echo "### CONFIGURE ELASTICSEARCH ###"
-  dev magerun2 config:set catalog/search/elasticsearch7_server_hostname elasticsearch7 --lock-env
+  # echo "### CONFIGURE ELASTICSEARCH ###"
+  # dev magerun2 config:set catalog/search/elasticsearch7_server_hostname elasticsearch7 --lock-env
 
-  echo "### CONFIGURE BASE URL ###"
-  dev magerun2 config:set web/unsecure/base_url http://$PROJECT.magento2.localhost/ --lock-env
-  dev magerun2 config:set web/secure/base_url http://$PROJECT.magento2.localhost/ --lock-env
+  # echo "### CONFIGURE BASE URL ###"
+  # dev magerun2 config:set web/unsecure/base_url http://$PROJECT.magento2.localhost/ --lock-env
+  # dev magerun2 config:set web/secure/base_url http://$PROJECT.magento2.localhost/ --lock-env
 
-  echo "### CONFIGURE ADMIN SESSION LIFETIME ###"
-  dev magerun2 config:set admin/security/session_lifetime 31536000 --lock-env
+  # echo "### CONFIGURE ADMIN SESSION LIFETIME ###"
+  # dev magerun2 config:set admin/security/session_lifetime 31536000 --lock-env
 
-  echo "### CONFIGURE MFTF ###"
-  dev magerun2 config:set admin/security/use_form_key 0 --lock-env
-  dev magerun2 config:set admin/security/admin_account_sharing 1 --lock-env
-  dev magerun2 config:set cms/wysiwyg/enabled disabled --lock-env
-  dev magerun2 config:set web/seo/use_rewrites 1 --lock-env
+  # echo "### CONFIGURE MFTF ###"
+  # dev magerun2 config:set admin/security/use_form_key 0 --lock-env
+  # dev magerun2 config:set admin/security/admin_account_sharing 1 --lock-env
+  # dev magerun2 config:set cms/wysiwyg/enabled disabled --lock-env
+  # dev magerun2 config:set web/seo/use_rewrites 1 --lock-env
 
-  echo "### ENABLE TEMPLATE SYMLINK ###"
-  dev magerun2 config:set dev/template/allow_symlink 1 --lock-env
+  # echo "### ENABLE TEMPLATE SYMLINK ###"
+  # dev magerun2 config:set dev/template/allow_symlink 1 --lock-env
 
-  echo "### RUN SETUP UPGRADE ###"
-  dev magerun2 setup:upgrade
+  # echo "### RUN SETUP UPGRADE ###"
+  # dev magerun2 setup:upgrade
 
-  dev apply-patch
+  # dev apply-patch
 }
 
 while getopts "p:i:a:c:d:b:" OPT; do
